// <auto-generated />
using Cyclix.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cyclix.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.7");

            modelBuilder.Entity("Cyclix.Entities.Bike", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnotherOptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("BrandId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OptionId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bikes");
                });

            modelBuilder.Entity("Cyclix.Entities.Customer", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            City = "Ho Chi Minh",
                            Email = "abc@test.com",
                            FirstName = "Hung",
                            HouseNumber = "10",
                            LastName = "Pham",
                            PostCode = "700000",
                            Street = "Pham Hung",
                            Telephone = "1234567890"
                        });
                });

            modelBuilder.Entity("Cyclix.Entities.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Category = "type",
                            Name = "type 1"
                        },
                        new
                        {
                            Id = 2L,
                            Category = "type",
                            Name = "type 2"
                        },
                        new
                        {
                            Id = 3L,
                            Category = "type",
                            Name = "type 3"
                        },
                        new
                        {
                            Id = 4L,
                            Category = "brand",
                            Name = "brand 1"
                        },
                        new
                        {
                            Id = 5L,
                            Category = "brand",
                            Name = "brand 2"
                        },
                        new
                        {
                            Id = 6L,
                            Category = "brand",
                            Name = "brand 3"
                        },
                        new
                        {
                            Id = 7L,
                            Category = "service",
                            Name = "service 1"
                        },
                        new
                        {
                            Id = 8L,
                            Category = "service",
                            Name = "service 2"
                        },
                        new
                        {
                            Id = 9L,
                            Category = "service",
                            Name = "service 3"
                        },
                        new
                        {
                            Id = 10L,
                            Category = "option",
                            Name = "option 1"
                        },
                        new
                        {
                            Id = 11L,
                            Category = "option",
                            Name = "option 2"
                        },
                        new
                        {
                            Id = 12L,
                            Category = "option",
                            Name = "option 3"
                        },
                        new
                        {
                            Id = 13L,
                            Category = "option",
                            Name = "option 4"
                        },
                        new
                        {
                            Id = 14L,
                            Category = "option",
                            Name = "option 5"
                        },
                        new
                        {
                            Id = 15L,
                            Category = "option",
                            Name = "option 6"
                        },
                        new
                        {
                            Id = 16L,
                            Category = "package",
                            Name = "package 1"
                        },
                        new
                        {
                            Id = 17L,
                            Category = "package",
                            Name = "package 2"
                        },
                        new
                        {
                            Id = 18L,
                            Category = "another_option",
                            Name = "another option 1"
                        },
                        new
                        {
                            Id = 19L,
                            Category = "another_option",
                            Name = "another option 2"
                        });
                });

            modelBuilder.Entity("Cyclix.Entities.Bike", b =>
                {
                    b.HasOne("Cyclix.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });
#pragma warning restore 612, 618
        }
    }
}
